services:
  redis:
    container_name: "rungo-redis"
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  mysql:
    container_name: "rungo-mysql"
    image: mysql:5.7.30
    ports:
    - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e
      - MYSQL_DATABASE=orm_test
      - MYSQL_USER=rungo
      - MYSQL_PASSWORD=test

  postgresql:
    container_name: "rungo-postgresql"
    image: bitnami/postgresql:latest
    ports:
    - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  ssdb:
    container_name: "rungo-ssdb"
    image: tsl0922/ssdb
    environment:
      - SSDB_PORT=8888
    ports:
    - "8888:8888"
  memcache:
    container_name: "rungo-memcache"
    image: memcached
    ports:
    - "11211:11211"
  etcd:
    command: >
      sh -c "
      etcdctl put current.float 1.23
      && etcdctl put current.bool true
      && etcdctl put current.int 11
      && etcdctl put current.string hello
      && etcdctl put current.serialize.name test
      "
    container_name: "rungo-etcd"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    image: bitnami/etcd
    ports:
    - "2379:2379"
    - "2380:2380"